version: '3.8'

services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=production
    volumes:
      - .:/app
    restart: always